CREATE TABLE employee(
	employee_id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	POSITIION VARCHAR(50),
	DEPARTMENT VARCHAR(50),
	HIRE_DATE DATE,
	SALARY NUMERIC(10,2)
);

SELECT * FROM employee;
